name: python-extract-java
description: This is an action to assign yourself to an issue for a repo you are not a contributor to.
author: Hackerghost
branding:
  icon: 'thumbs-up'
  color: 'white'
inputs:
  repo-token:
    description: "The GITHUB_TOKEN repo secret"

runs:
  using: "composite"
  steps:
      - name: Download DesigniteJava
        run: wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
      - name: Analyze project with DesigniteJava
        run: |
          java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ secrets.PAT }} 
          ls
          curl -X PUT -H "Authorization: Token ${{ secrets.QSCORED_API_KEY }}" -H "repository-link:https://github.com/" + GITHUB_REPOSITORY -H "username: " -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$GITHUB_RUN_NUMBER&project_name=" -F "file=@Designite_output/DesigniteAnalysis.xml"
  
